# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LoadList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, load1: float=None, load2: float=None, load3: float=None):  # noqa: E501
        """LoadList - a model defined in Swagger

        :param load1: The load1 of this LoadList.  # noqa: E501
        :type load1: float
        :param load2: The load2 of this LoadList.  # noqa: E501
        :type load2: float
        :param load3: The load3 of this LoadList.  # noqa: E501
        :type load3: float
        """
        self.swagger_types = {
            'load1': float,
            'load2': float,
            'load3': float
        }

        self.attribute_map = {
            'load1': 'load1',
            'load2': 'load2',
            'load3': 'load3'
        }
        self._load1 = load1
        self._load2 = load2
        self._load3 = load3

    @classmethod
    def from_dict(cls, dikt) -> 'LoadList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoadList of this LoadList.  # noqa: E501
        :rtype: LoadList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def load1(self) -> float:
        """Gets the load1 of this LoadList.

        Load 1  # noqa: E501

        :return: The load1 of this LoadList.
        :rtype: float
        """
        return self._load1

    @load1.setter
    def load1(self, load1: float):
        """Sets the load1 of this LoadList.

        Load 1  # noqa: E501

        :param load1: The load1 of this LoadList.
        :type load1: float
        """

        self._load1 = load1

    @property
    def load2(self) -> float:
        """Gets the load2 of this LoadList.

        Load 2  # noqa: E501

        :return: The load2 of this LoadList.
        :rtype: float
        """
        return self._load2

    @load2.setter
    def load2(self, load2: float):
        """Sets the load2 of this LoadList.

        Load 2  # noqa: E501

        :param load2: The load2 of this LoadList.
        :type load2: float
        """

        self._load2 = load2

    @property
    def load3(self) -> float:
        """Gets the load3 of this LoadList.

        Load 3  # noqa: E501

        :return: The load3 of this LoadList.
        :rtype: float
        """
        return self._load3

    @load3.setter
    def load3(self, load3: float):
        """Sets the load3 of this LoadList.

        Load 3  # noqa: E501

        :param load3: The load3 of this LoadList.
        :type load3: float
        """

        self._load3 = load3
