# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ParameterList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, param1: float=None, param2: float=None, param3: float=None):  # noqa: E501
        """ParameterList - a model defined in Swagger

        :param param1: The param1 of this ParameterList.  # noqa: E501
        :type param1: float
        :param param2: The param2 of this ParameterList.  # noqa: E501
        :type param2: float
        :param param3: The param3 of this ParameterList.  # noqa: E501
        :type param3: float
        """
        self.swagger_types = {
            'param1': float,
            'param2': float,
            'param3': float
        }

        self.attribute_map = {
            'param1': 'param1',
            'param2': 'param2',
            'param3': 'param3'
        }
        self._param1 = param1
        self._param2 = param2
        self._param3 = param3

    @classmethod
    def from_dict(cls, dikt) -> 'ParameterList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ParameterList of this ParameterList.  # noqa: E501
        :rtype: ParameterList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def param1(self) -> float:
        """Gets the param1 of this ParameterList.

        Parameter 1  # noqa: E501

        :return: The param1 of this ParameterList.
        :rtype: float
        """
        return self._param1

    @param1.setter
    def param1(self, param1: float):
        """Sets the param1 of this ParameterList.

        Parameter 1  # noqa: E501

        :param param1: The param1 of this ParameterList.
        :type param1: float
        """

        self._param1 = param1

    @property
    def param2(self) -> float:
        """Gets the param2 of this ParameterList.

        Parameter 2  # noqa: E501

        :return: The param2 of this ParameterList.
        :rtype: float
        """
        return self._param2

    @param2.setter
    def param2(self, param2: float):
        """Sets the param2 of this ParameterList.

        Parameter 2  # noqa: E501

        :param param2: The param2 of this ParameterList.
        :type param2: float
        """

        self._param2 = param2

    @property
    def param3(self) -> float:
        """Gets the param3 of this ParameterList.

        Parameter 3  # noqa: E501

        :return: The param3 of this ParameterList.
        :rtype: float
        """
        return self._param3

    @param3.setter
    def param3(self, param3: float):
        """Sets the param3 of this ParameterList.

        Parameter 3  # noqa: E501

        :param param3: The param3 of this ParameterList.
        :type param3: float
        """

        self._param3 = param3
